import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

// ... (previous imports)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F5F5F7]`}
      >
        {/* Global Header - Apple Style Glass */}
        <div className="fixed top-0 left-0 right-0 z-50 bg-[#F5F5F7]/80 backdrop-blur-md border-b border-[#0000000d] transition-all duration-300">
          <div className="max-w-[1600px] mx-auto px-6 lg:px-12 h-[48px] flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2 group">
              <div className="w-5 h-5 bg-[#1d1d1f] rounded text-white flex items-center justify-center text-[10px] font-bold">N</div>
              <span className="font-semibold text-[13px] tracking-wide text-[#1d1d1f] group-hover:text-[#06c] transition-colors">NoiseReduction</span>
            </Link>

            {/* Navigation Links - Scrollable on Mobile */}
            <div className="flex gap-6 lg:gap-8 text-[12px] font-medium text-[#1d1d1f]/80 overflow-x-auto whitespace-nowrap scrollbar-hide ml-4 lg:ml-0 pr-4 lg:pr-0 items-center h-full">
              <Link href="/" className="hover:text-[#06c] transition-colors shrink-0">Curated</Link>
              <Link href="/courses" className="hover:text-[#06c] transition-colors text-purple-600 font-semibold shrink-0">Courses 🆕</Link>
              <Link href="/lingo" className="hover:text-[#06c] transition-colors text-orange-500 font-semibold shrink-0">Lingo 📺</Link>
              <Link href="/friends" className="hover:text-[#06c] transition-colors text-[#7B538C] font-semibold shrink-0">Friends 🍕</Link>
              <Link href="/favorites" className="hover:text-[#06c] transition-colors shrink-0">Favorites</Link>
            </div>

            {/* Scrollbar Hide Style */}
            <style jsx global>{`
              .scrollbar-hide::-webkit-scrollbar {
                  display: none;
              }
              .scrollbar-hide {
                  -ms-overflow-style: none;
                  scrollbar-width: none;
              }
            `}</style>
          </div>
        </div>

        <div className="pt-[48px]">
          {children}
        </div>
      </body>
    </html>
  );
}
